### ISSUE TITLE
Lesson 7 Typo/Bug

### ISSUE THREAD

**Issue by erik-rosenstrom** [HHS/ASPR-8#247]
The getUnvaccinatedFamilyMembers query in the VaccinationDataManager of Lesson 7 seems to append the incorrect id to the result list. Should the result list add the familyMemberId rather than the personId as follows:

result.add(familyMemeberId);

**Comment by bischoffz** [comment]
Will Take a look at this, thanks!

**Comment by bischoffz** [comment]
This has been fixed in #251 and will be in the next general release in about a month. Thanks for finding this!
